# Generated by Django 4.1.2 on 2022-10-31 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investasiku', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portofolio',
            name='investment',
        ),
        migrations.AddField(
            model_name='portofolio',
            name='investment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='investasiku.investment'),
        ),
    ]
