# Generated by Django 4.1.2 on 2022-11-01 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investasiku', '0002_remove_portofolio_investment_portofolio_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investasiku.investment'),
        ),
    ]
