version: "3.9"

services:
  postgres:
    image: postgres
    container_name: duitku-postgres
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: "300m"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - duitku-postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432" 

volumes:
  duitku-postgres:
