# Generated by Django 4.1.2 on 2022-10-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_transaction_actor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="description",
        ),
    ]
