# Generated by Django 4.1.2 on 2022-10-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_remove_wallet_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
