# Generated by Django 4.1.2 on 2022-11-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_wallet_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(default="Default transaction", max_length=50),
            preserve_default=False,
        ),
    ]
